# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'environment',
            },
        ),
        migrations.CreateModel(
            name='LiveBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('url', models.URLField(help_text="The URL of the blog in the LiveBlog environment.")),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('access_type', models.CharField(choices=[('f', 'Gratuito'), ('s', 'Para suscripciones pagas')], default='s', max_length=1, verbose_name='access')),
                ('in_home', models.BooleanField(default=False, verbose_name='featured in home')),
                ('notification', models.BooleanField(default=False, verbose_name='articles notification')),
                ('notification_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='notification text')),
                ('notification_url', models.URLField(blank=True, null=True, verbose_name='notification url')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utopia_cms_liveblog.Environment')),
            ],
            options={
                'verbose_name': 'live blog',
                'verbose_name_plural': 'live blogs',
            },
        ),
    ]
