# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-08 23:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_liveblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='liveblog',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
    ]
