# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20201220_1312'),
        ('utopia_cms_liveblog', '0002_auto_20221108_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo', verbose_name='photo'),
        ),
    ]
