# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_liveblog', '0003_liveblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
