# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20221117_0412'),
        ('utopia_cms_liveblog', '0004_liveblog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveblog',
            options={'ordering': ('-day',), 'verbose_name': 'live blog', 'verbose_name_plural': 'live blogs'},
        ),
        migrations.RemoveField(
            model_name='liveblog',
            name='active',
        ),
        migrations.AddField(
            model_name='liveblog',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='liveblog',
            name='notification_target_pubs',
            field=models.ManyToManyField(to='core.Publication', verbose_name='notification target publications'),
        ),
        migrations.AddField(
            model_name='liveblog',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('to_begin', 'to begin'), ('active', 'active'), ('ended', 'ended')], default='idle', max_length=8, verbose_name='status'),
        ),
    ]
