# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_liveblog', '0007_auto_20221123_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='location',
            field=models.CharField(default='', max_length=128, verbose_name='location'),
            preserve_default=False,
        ),
    ]
