# Generated by Django 4.1.4 on 2024-06-27 21:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utopia_cms_liveblog", "0008_liveblog_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveblog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
