# Generated by Django 4.1.4 on 2024-06-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utopia_cms_liveblog", "0009_alter_liveblog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveblog",
            name="title",
            field=models.CharField(
                help_text="Enter a concise and descriptive title. It is recommended not to change the title once it has been entered, as this may affect the blog's search engine ranking due to potential delays in cache updates.",
                max_length=128,
                unique=True,
                verbose_name="title",
            ),
        ),
    ]
