# Generated by Django 4.1.13 on 2024-10-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utopia_cms_liveblog", "0010_alter_liveblog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveblog",
            name="alt_desc_meta",
            field=models.TextField(
                blank=True,
                help_text="Applies to the content of the description meta tag in the &lt;head&gt; of the article page.<br>If left blank, the main description is applied.",
                null=True,
                verbose_name="alternative description for metadata",
            ),
        ),
        migrations.AddField(
            model_name="liveblog",
            name="alt_desc_og_meta",
            field=models.TextField(
                blank=True,
                help_text="Applies to metadata: Open Graph and Schema in the &lt;head&gt; of the article page.<br>If left blank, the main description is applied.",
                null=True,
                verbose_name="alternative description for og metadata",
            ),
        ),
        migrations.AddField(
            model_name="liveblog",
            name="alt_title",
            field=models.CharField(
                blank=True,
                help_text="Applies to title tag in the &lt;head&gt; of the article page.<br>If left blank, the main title is applied.",
                max_length=200,
                null=True,
                verbose_name="alternative title",
            ),
        ),
        migrations.AddField(
            model_name="liveblog",
            name="alt_title_meta",
            field=models.CharField(
                blank=True,
                help_text="Applies to metadata: meta title, Open Graph and Schema in the &lt;head&gt; of the article page.<br>If left blank, the main title is applied.",
                max_length=200,
                null=True,
                verbose_name="alternative title for metadata",
            ),
        ),
        migrations.AlterField(
            model_name="liveblog",
            name="title",
            field=models.CharField(
                help_text="Enter a concise and descriptive title.",
                max_length=128,
                unique=True,
                verbose_name="title",
            ),
        ),
        migrations.CreateModel(
            name="LiveBlogUrlHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absolute_url", models.URLField(db_index=True, max_length=500)),
                (
                    "liveblog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utopia_cms_liveblog.liveblog",
                    ),
                ),
            ],
            options={
                "unique_together": {("liveblog", "absolute_url")},
            },
        ),
    ]
