# Generated by Django 4.1.13 on 2024-10-29 08:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "utopia_cms_liveblog",
            "0011_liveblog_alt_desc_meta_liveblog_alt_desc_og_meta_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveblog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                max_length=200,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
