# Generated by Django 4.2.19 on 2025-02-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utopia_cms_liveblog", "0012_alter_liveblog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveblog",
            name="access_type",
            field=models.CharField(
                choices=[("f", "Free"), ("s", "Paid subscriptions only")],
                default="f",
                help_text="'Paid subscriptions only' option has effect only when the blog is featured in home, when selected, only subscribers will see the blog live timeline in the site home page.",
                max_length=1,
                verbose_name="access",
            ),
        ),
    ]
